### ISSUE TITLE
How can I change to different image size?

### ISSUE THREAD

**Issue by caichunjian520** [dbsystel/yolov5-coreml-tools#8]
My trained model image size is 704 x 704, and I tried to search "640" in src/coreml_export/main.py and replace with 704. The output mlmodel is Okay. 

But when I use this mlmodel, it can't detect anything.

I have no idea how to change 640 x 640 to different size. Any help?

**Comment by Leon0402** [comment]
Have a look at #1, you cannot just replace the image resolution that won't workt. PRs are welcome.
